"use client";

//import { Navbar } from "@/components/Navbar";
//import { Sidebar } from "@/components/Sidebar";
import { ChangeEvent } from "react";
import { useState } from "react";

export default function Patients() {
  const [activeTab, setActiveTab] = useState("overview");

  // ========================
  // 👤 PATIENT PROFILE STATE
  // ========================
  const [profile, setProfile] = useState({
    name: "WEAH",
    email: "weah@gmail.com.com",
    location: "Douala",
    dob: "2006-06-15",
    gender: "FEMALE",
  });

  const doctors = [
    { name: "Dr. Smith", specialty: "Cardiologist", available: "10:00 - 12:00" },
    { name: "Dr. Brown", specialty: "General", available: "14:00 - 16:00" },
    { name: "Dr. Adams", specialty: "Neurologist", available: "09:00 - 11:00" },
  ];


  type Appointment = {
    doctor: string;
    specialty: string;
    time: string;
    date: string;
  };

  const [appointments, setAppointments] = useState<Appointment[]>([]);

  type Doctor = {
    name: string;
    specialty: string;
    available: string;
  };

  const bookAppointment = (doctor: Doctor) => {
    const newAppointment = {
      doctor: doctor.name,
      specialty: doctor.specialty,
      time: doctor.available,
      date: new Date().toLocaleDateString(),
    };

    setAppointments([...appointments, newAppointment]);
    alert(`Appointment booked with ${doctor.name}`);
  };

  const handleProfileChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setProfile({
      ...profile,
      [e.target.name]: e.target.value,
    });
  };



  return (
    <div className="min-h-screen flex bg-green-50">

      {/* LEFT SIDEBAR (PATIENT PROFILE) */}
      <aside className="w-80 bg-green-900 text-white p-6 flex flex-col gap-6">

        {/* Profile */}
        <div className="text-center">
          <div className="w-24 h-24 mx-auto rounded-full bg-green-700 mb-3"></div>
          <h2 className="text-xl font-bold">{profile.name}</h2>
          <p className="text-sm text-green-200">Patient</p>
          <p className="text-sm text-green-200">Patient ID: PT-1024</p>
        </div>

        <div className="text-sm space-y-1">
          <p><b>Email:</b> {profile.email}</p>
          <p><b>Location:</b> {profile.location}</p>
          <p><b>DOB:</b> {profile.dob}</p>
          <p><b>Gender:</b> {profile.gender}</p>
        </div>

        {/* Navigation */}
        <div className="mt-4 space-y-2">
          {[
            "overview",
            "appointments",
            "lab",
            "referrals",
            "medication",
            "allergies",
            "documents",
            "edit profile",
          ].map((item) => (
            <button
              key={item}
              onClick={() => setActiveTab(item)}
              className={`w-full text-left px-3 py-2 rounded hover:bg-green-800 transition ${activeTab === item ? "bg-green-800" : ""
                }`}
            >
              {item.toUpperCase()}
            </button>
          ))}
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <div className="flex-1 flex flex-col">

        {/* NAVBAR */}
        <div className="bg-green-800 text-white px-6 py-4 flex justify-between items-center">
          <h1 className="font-bold">Patient Dashboard</h1>
          <button className="bg-white text-green-900 px-4 py-1 rounded">
            Logout
          </button>
        </div>

        {/* CONTENT AREA */}
        <div className="p-6 text-black">

          {/* OVERVIEW */}
          {activeTab === "overview" && (
            <div className="space-y-6">

              <h2 className="text-2xl font-bold text-green-900">
                Health Record Overview
              </h2>

              {/* Current Health Record */}
              <div className="bg-white p-4 rounded-xl shadow border-l-4 border-green-800">
                <h3 className="font-semibold">Current Health Record</h3>
                <p>Generated by: City Hospital</p>
                <p>Condition: Stable</p>
                <p>Last Visit: 20/04/2026</p>
              </div>

              {/* History */}
              <div className="bg-white p-4 rounded-xl shadow">
                <h3 className="font-semibold mb-2">Health History</h3>
                <ul className="list-disc ml-5">
                  <li>2025 - Hypertension diagnosed</li>
                  <li>2024 - Routine checkup normal</li>
                  <li>2023 - Minor surgery (appendectomy)</li>
                </ul>
              </div>

            </div>
          )}

          {/* ================= APPOINTMENTS ================= */}
          {activeTab === "appointments" && (
            <div>

              <h2 className="text-xl font-bold text-green-900 mb-4">
                Book Appointment
              </h2>

              {/* DOCTOR LIST */}
              <div className="grid gap-3">
                {doctors.map((doc, i) => (
                  <div
                    key={i}
                    className="bg-white p-4 rounded shadow flex justify-between items-center"
                  >
                    <div>
                      <p className="font-bold">{doc.name}</p>
                      <p className="text-sm">{doc.specialty}</p>
                      <p className="text-sm text-gray-600">
                        Available: {doc.available}
                      </p>
                    </div>

                    <button
                      onClick={() => bookAppointment(doc)}
                      className="bg-green-800 text-white px-3 py-2 rounded hover:bg-green-900"
                    >
                      Book
                    </button>
                  </div>
                ))}
              </div>

              {/* APPOINTMENT LIST */}
              <h3 className="mt-6 font-bold text-green-900">
                My Appointments
              </h3>

              <div className="mt-2 space-y-2">
                {appointments.map((a, i) => (
                  <div key={i} className="bg-white p-3 rounded shadow">
                    <p><b>Doctor:</b> {a.doctor}</p>
                    <p><b>Time:</b> {a.time}</p>
                    <p><b>Date:</b> {a.date}</p>
                  </div>
                ))}
              </div>

            </div>
          )}

          {/* LAB RESULTS */}
          {activeTab === "lab" && (
            <div className="bg-white p-4 rounded-xl shadow">
              <h2 className="font-bold text-green-900 mb-2">Lab Results</h2>
              <p>No new results available</p>
            </div>
          )}

          {/* REFERRALS */}
          {activeTab === "referrals" && (
            <div className="bg-white p-4 rounded-xl shadow">
              <h2 className="font-bold text-green-900">Referrals</h2>
              <p>No referrals at this time</p>
            </div>
          )}

          {/* MEDICATION */}
          {activeTab === "medication" && (
            <div className="bg-white p-4 rounded-xl shadow">
              <h2 className="font-bold text-green-900">Current Medication</h2>
              <ul className="list-disc ml-5">
                <li>Paracetamol - 500mg</li>
                <li>Amlodipine - 5mg</li>
              </ul>
            </div>
          )}

          {/* ALLERGIES */}
          {activeTab === "allergies" && (
            <div className="bg-white p-4 rounded-xl shadow">
              <h2 className="font-bold text-green-900">Allergies</h2>
              <p>Penicillin</p>
            </div>
          )}

          {/* DOCUMENTS */}
          {activeTab === "documents" && (
            <div className="bg-white p-4 rounded-xl shadow">
              <h2 className="font-bold text-green-900">
                About Our System
              </h2>
              <p>
                The National Health Records Management System (NHRMS)
                securely stores patient data, enabling hospitals and patients
                to access real-time medical information.
              </p>
            </div>
          )}

          {/* EDIT PROFILE */}
          {/* ================= EDIT PROFILE ================= */}
          {activeTab === "edit profile" && (
            <div className="bg-white p-4 rounded shadow space-y-3">

              <h2 className="text-xl font-bold text-green-900">
                Edit Profile
              </h2>

              <input
                name="name"
                value={profile.name}
                onChange={handleProfileChange}
                className="w-full p-2 border rounded"
                placeholder="Name"
              />

              <input
                name="email"
                value={profile.email}
                onChange={handleProfileChange}
                className="w-full p-2 border rounded"
                placeholder="Email"
              />

              <input
                name="location"
                value={profile.location}
                onChange={handleProfileChange}
                className="w-full p-2 border rounded"
                placeholder="Location"
              />

              <input
                name="dob"
                value={profile.dob}
                onChange={handleProfileChange}
                className="w-full p-2 border rounded"
                placeholder="DOB"
              />

              <select
                name="gender"
                value={profile.gender}
                onChange={handleProfileChange}
                className="w-full p-2 border rounded"
              >
                <option>Male</option>
                <option>Female</option>
              </select>

            </div>
          )}


        </div>
      </div>
    </div>
  );
}




